# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET CI

on:
  push:
    branches: [ "main" ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
  
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Restore dependencies
      run: dotnet restore ./src/experimental-project.sln

    - name: Build
      run: dotnet build ./src/experimental-project.sln --no-restore --configuration Release

    - name: Test
      run: dotnet test ./src/experimental.api.tests/experimental.api.tests.csproj --no-build --verbosity normal --configuration Release

    - name: Publish the app
      run: dotnet publish ./src/experimental.api/experimental.api.csproj -c Release -o ./publish --no-build

    - name: Publish to GitHub Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          # ./publish/*.zip # ”кажите путь к файлам, которые вы хотите прикрепить к релизу
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
